substitutions:
  device_name: solartemp
  mqtt_prefix: solarheating

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  #includes:
  #  - solartemp.h

spi:
  miso_pin: D6
  mosi_pin: D7
  clk_pin: D5


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: p1reader.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-${device_name}"
    password: !secret solartemp_password

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0 # disable logging over uart

# Enable Home Assistant API
#api:
#  password: !secret solartemp_password

ota:
  password: !secret solartemp_password

mqtt:
  broker: 192.150.23.16
#  username: villaelmerfjord
#  password: !secret mqtt_password
  port: 8883
  topic_prefix: solarheating
  # discovery: false
  discovery: true
  discovery_prefix: ${mqtt_prefix} #/homeassistant
  log_topic: ${mqtt_prefix}/logs
  
web_server:
  port: 80
  ota: false
#  auth:
#    username: admin
#    password: !secret solartemp_password

prometheus:

text_sensor:
# Reports the ESPHome Version with compile date
  - platform: version
    name: "${device_name} ESPHome Version"


# number:
#   - platform: template
#     name: "${device_name} update period"
#     id: p1_period
#     icon: "mdi:timer"
#     unit_of_measurement: s
#     optimistic: true
#     restore_value: true
#     min_value: 0
#     max_value: 20
#     step: 0.25
#     initial_value: 2 # Set to your desired update period (in seconds)
#     internal: false # Set to true to hide setting from Home Assistant etc.


sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    id: solarpanel_wifi
    update_interval: 30s
    on_value:
      - mqtt.publish_json:
          topic: "solarheating/wifi_signal"
          payload: |-
            root["wifi_signal"] = id(solarpanel_wifi).state;
  - platform: max31865
    name: "Solarpanel Temp Left"
    id: sp_temp_left
    cs_pin: D2
    reference_resistance: 4300 Ω
    rtd_nominal_resistance: 1000 Ω
    on_value:
      - mqtt.publish_json:
          topic: "solarheating/temperature"
          payload: |-
            root["PanelLeft"] = id(sp_temp_left).state;
  - platform: max31865
    name: "Solarpanel Temp Middle"
    id: sp_temp_mid
    cs_pin: D3
    reference_resistance: 4300 Ω
    rtd_nominal_resistance: 1000 Ω
    on_value:
      - mqtt.publish_json:
          topic: "solarheating/temperature"
          payload: |-
            root["PanelMiddle"] = id(sp_temp_mid).state;
   
  - platform: max31865
    name: "Solarpanel Temp Right"
    id: sp_temp_right
    cs_pin: D1
    reference_resistance: 4300 Ω
    rtd_nominal_resistance: 1000 Ω
    on_value:
      - mqtt.publish_json:
          topic: "solarheating/temperature"
          payload: |-
            root["PanelRight"] = id(sp_temp_right).state;
